version: '3'
services:
  lazy-frontend:
    build: .
    container_name: lazy-todo
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
